figure(10)
subplot(2,3,1)
scatter(anData.timeStart,anData.totalCount) 
subplot(2,3,2)
scatter(anData.timeStart, anData.TWConcentraction)
subplot(2,3,3)
scatter(anData.timeStart,anData.sample.Number) 
subplot(2,3,4)
scatter(anData.timeStart, anData.sample.VolumeAll)
subplot(2,3,5)
scatter(anData.timeStart,anData.sample.NumberReal) 
subplot(2,3,6)
scatter(anData.timeStart, anData.sample.VolumeReal)