function [TimePVM5minUTC,PVM_Man_LWC5min,CDP_Man_LWC5min] = importManchesterCorr(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIMEPVM5MINUTC,PVM_MAN_LWC5MIN,CDP_MAN_LWC5MIN] = IMPORTFILE(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   [TIMEPVM5MINUTC,PVM_MAN_LWC5MIN,CDP_MAN_LWC5MIN] = IMPORTFILE(FILENAME,
%   STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text
%   file FILENAME.
%
% Example:
%   [TimePVM5minUTC,PVM_Man_LWC5min,CDP_Man_LWC5min] =
%   importfile('PVM_CDP_UManchester_CorrectedData.txt',4, 7469);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2013/10/24 15:04:52

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 4;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
TimePVM5minUTC = dataArray{:, 1};
PVM_Man_LWC5min = dataArray{:, 2};
CDP_Man_LWC5min = dataArray{:, 3};

