function [pStats] = predictClassHOLOLAB(pStats)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

%Predict Class of Particles
    tree = load('F:\HOLOLAB\10_28_ms-files\ClassificatonTreeNeu.mat');
    tree = tree.treeFile;
    
%     treeX = [pStats.minPh; pStats.maxPh; ...
%         pStats.minAmp; pStats.maxAmp; ...
%         pStats.pDiamMean; pStats.imStdAngles;...
%         pStats.imPerimRatio; pStats.imEccentricity;...
%         pStats.imSolidity; pStats.imMeanRadii;...
%         pStats.imStdRadii; pStats.imEquivDiaOldSizes;...
%         pStats.pDiamOldThresh]';
    
    treeHX = [pStats.minPh ; pStats.maxPh; ...
        pStats.minAmp; pStats.maxAmp; ...
        pStats.pDiamMean;
        pStats.imStdAngles;...
        pStats.imPerimRatio; pStats.imEccentricity;...
        pStats.imSolidity; pStats.imMeanRadii;...
        pStats.imStdRadii; pStats.imEquivDiaOldSizes;...
        pStats.pDiamOldThresh; pStats.rtDp;...
        pStats.rtBSlope; pStats.rtSignal;...
        pStats.rtGoodFit; pStats.rtAsym;...
        pStats.imStdmRadii; pStats.imStdmAngles...
        ]';
    

        pStats.predictedHClass = predict(tree.classificationHTree, treeHX)';
        
        pStats.predictedHClass(~pStats.partIsReal) = 'Artefact';
        pStats.predictedHClass(isnan(pStats.pDiamOldSizesOldThresh)) = 'Artefact';
        
        pStats.predictedHClass(pStats.predictedHClass=='Ice' & ...
            pStats.pDiamOldSizesOldThresh < 19.2896*1e-6) ...
            = 'Artefact';
        pStats.predictedHClass(pStats.predictedHClass=='Ice' & ...
            pStats.pDiamOldSizesOldThresh < 87.9*1e-6) ...
            = 'Small Ice';
        pStats.predictedHClass(pStats.predictedHClass=='Water' & ...
            pStats.pDiamOldSizesOldThresh < 75*1e-6) ...
            = 'Small Water';

end

