function [pStats] = predictClass(pStats)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

%Predict Class of Particles
    tree = load('Z:\6_Auswertung\ALL\ClassificatonTreeNeu.mat');
    tree = tree.treeFile;
    
%     treeX = [pStats.minPh; pStats.maxPh; ...
%         pStats.minAmp; pStats.maxAmp; ...
%         pStats.pDiamMean; pStats.imStdAngles;...
%         pStats.imPerimRatio; pStats.imEccentricity;...
%         pStats.imSolidity; pStats.imMeanRadii;...
%         pStats.imStdRadii; pStats.imEquivDiaOldSizes;...
%         pStats.pDiamOldThresh]';
    
    treeHX = [pStats.minPh ; pStats.maxPh; ...
        pStats.minAmp; pStats.maxAmp; ...
        pStats.pDiamMean;
        pStats.imStdAngles;...
        pStats.imPerimRatio; pStats.imEccentricity;...
        pStats.imSolidity; pStats.imMeanRadii;...
        pStats.imStdRadii; pStats.imEquivDiaOldSizes;...
        pStats.pDiamOldThresh; pStats.rtDp;...
        pStats.rtBSlope; pStats.rtSignal;...
        pStats.rtGoodFit; pStats.rtAsym;...
        pStats.imStdmRadii; pStats.imStdmAngles...
        ]';
    

        pStats.predictedHClass = predict(tree.classificationHTree, treeHX)';
        
        pStats.predictedHClass(pStats.predictedHClass=='Ice' & ...
            pStats.imEquivDiaOldSizes < 19.2896*1e-6) = 'Artefact';

end

